DATASET:
  upsamplingFactor: 4 # from heatmaps (64 x 64) to RGB (256 x 256)
  duration: 300
  heatmap_size: 64
  imgSize: 256
  img_heatmap_ratio: 4
  rangeSize: 64
  azimuthSize: 64
  elevationSize: 8
  num_keypoints: 14
  numFrames: 8 # num of chirps in one frame to be processed
  num_group_frames: 8 # num of frames to be processed
  performDopplerFFT: True
  numChirps: 64 # num of chirps captured by radar sensors, should always be 16
  log_dir: '/root/log'
  dataDir: '/root/proc_data/HuPR_collected/' #'../radar_skeleton_estimation_iwr1843/data/20220623'
  trainName: [
    1, 2, 3, 4, 5, 6, 7, 8, 9, 
    11, 12, 13, 14, 15, 16, 17, 18, 19, 
    22, 23, 24, 25, 25, 27, 28, 29, # 21 is deprecated
    31, 32, 33, 34, 35, 36, 37, 38, 39,  
    41, 42, 43, 44, 45, 46, 47, 48, 49,  
    51, 52, 53, 54, 55, 56, 57, 58, 59,  
    61, 62, 63, 64, 65, 66, 67, 68, 69,  
    71, 72, 73, 74, 75, 76, 77, 78, 79, 
    ]
  valName: [10, 20, 30, 40, 50, 60, 70]
  testName: [10, 20, 30, 40, 50, 60, 70]
  idx_to_joints: ["R_Hip", "R_Knee", "R_Ankle", "L_Hip", "L_Knee", "L_Ankle", "Neck", "Head", "L_Shoulder", "L_Elbow", "L_Wrist", "R_Shoulder", "R_Elbow", "R_Wrist"]
MODEL:
  runClassification: False
  preLoad: False
  num_filters: 32
  add_position_embedding: True
  weightPath: '/root/log/pretrained_weights/mscsa_prgcn.ckpt'
TRAINING:
  batch_size: 24
  epochs: 20
  lr: 0.0001
  warmup_epoch: -1
  warmup_growth: 1.005
  lr_decay: 0.999
  lr_decayIter: 2000
  loss_decay: -1
  use_weight: False
  optimizer: "adam"
TEST:
  batch_size: 32
  plotImgDir: '/root/raw_data/demo/'
SETUP:
  num_workers: 1
